### PR TITLE
Upgrade deps to support description in SDL

### PR DESCRIPTION
**Pull request by tgriesser**
Descriptions are now correctly defined/parsed as quoted strings [preceding the node](https://github.com/graphql/graphql-js/pull/927).

ArgumentsOfCorrectType became ValuesOfCorrectType in 0.12

Upgraded dependencies:
- graphql-language-service-interface: 0.0.11 -> 1.0.18
- graphql-language-service-parser: 0.0.10 -> 1.0.18
- graphql: 0.9.6 -> 0.12.3
- apollo-codegen:  0.10.13 -> 0.18.8

### CODE REVIEW

**Comment by tgriesser** [comment]
This PR is an attempt to get rid of the errors I'm seeing when using the new description syntax in my GraphQL schema definition file. I've been working the changes on this branch locally and it seems to do the trick.

screen shot 2018-03-05 at 11 08 06 am
screen shot 2018-03-05 at 11 07 23 am

**Comment by Mayank1791989** [comment]
Hi @tgriesser  thanks for the PR. 

But there are few issues with graphql >0.12.x 
- as description becomes part of ast the current printer will not print correctly
  (info shown in tooltips will be broken).
- also it will break the old comment description syntax.

The proper fix is already in v3 branch (I will try to release it as soon as possible). For now anyone who is using the new description can use your fork to avoid parsing error.

**Comment by ajhyndman** [comment]
@Mayank1791989 Are you interested in any contributions assisting with the v3 project?  Is there any way we can help keep that moving?

**Comment by tgriesser** [comment]
I just upgraded this to GraphQL 0.13, anyone that needs it can use  
```
"@playlyfe/gql": "tgriesser/gql.git#upgrade-deps-published-0.13",
```
in their package.json

**Comment by tgriesser** [comment]
Nevermind, the changes here seem to break things, couldn't figure out why exactly. I think it might have to do with the fact that the language service is still on `^0.12`? 

Anyway, closing this since it's not going to be merged as is. 

Looks like there's some good work being done on the [graphql-for-vscode](https://github.com/kumarharsh/graphql-for-vscode/commit/774628f10a39e66fd3de9c59b14f4fc3cd5c8348) related to this. Looking forward to it!

**Pull request closed without merging**
